#!/usr/bin/env node
/**
 * legal/*.md  ->  server/src/lib/legalText.ts + mobile/lib/legalText.ts
 *
 * Why generate rather than read the files at runtime:
 *
 *   - The server's Docker build context is `server/`. A runtime read of
 *     `../legal/terms.md` works on a laptop and 404s in production, which is
 *     the worst place to discover that the privacy policy is missing.
 *   - The app must show the Terms BEFORE sign-in, offline, on a phone that has
 *     never reached the server. Only text bundled into the JS can do that.
 *
 * So the markdown in legal/ is the one source, and both copies — and the one
 * LEGAL_VERSION both sides compare consent against — are stamped out of it
 * here. The server test suite compares its copy with legal/ and fails if this
 * was not re-run after an edit.
 *
 * Usage (from anywhere):   node tools/legal/sync.mjs
 *         check only:       node tools/legal/sync.mjs --check
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const DOCS = ['terms', 'privacy', 'dmca', 'community'];

const version = readFileSync(join(root, 'legal', 'VERSION'), 'utf8').trim();
if (!/^\d{4}-\d{2}-\d{2}$/.test(version)) {
  console.error(`legal/VERSION must be a YYYY-MM-DD date, got "${version}"`);
  process.exit(1);
}

/** Strip repo-only comments; the header notes are for us, not for players. */
function clean(markdown) {
  return markdown.replace(/<!--[\s\S]*?-->/g, '').replace(/\r\n/g, '\n').trim() + '\n';
}

const docs = {};
for (const key of DOCS) {
  const markdown = clean(readFileSync(join(root, 'legal', `${key}.md`), 'utf8'));
  const title = /^#\s+(.+)$/m.exec(markdown)?.[1]?.trim();
  if (!title) {
    console.error(`legal/${key}.md has no "# Title" line`);
    process.exit(1);
  }
  docs[key] = { title, markdown };
}

function render(consumer) {
  return `/**
 * GENERATED by tools/legal/sync.mjs from legal/*.md — do not edit by hand.
 *
 * Edit the markdown in legal/, bump legal/VERSION for a material change, and
 * re-run \`node tools/legal/sync.mjs\`. ${consumer}
 */

/**
 * The version of the Terms and Privacy Policy a player is agreeing to.
 *
 * Both the server and the app carry this constant, generated from the same
 * legal/VERSION file. The server records it on the user at consent; when it
 * moves, every player whose recorded version differs is asked again.
 */
export const LEGAL_VERSION = ${JSON.stringify(version)};

export type LegalDocKey = ${DOCS.map((d) => JSON.stringify(d)).join(' | ')};

export const LEGAL_DOC_KEYS: readonly LegalDocKey[] = ${JSON.stringify(DOCS)};

export const LEGAL_DOCS: Record<LegalDocKey, { title: string; markdown: string }> = ${JSON.stringify(docs, null, 2)};
`;
}

const targets = [
  [join(root, 'server', 'src', 'lib', 'legalText.ts'), 'Served as HTML at /legal/*.'],
  [join(root, 'mobile', 'lib', 'legalText.ts'), 'Rendered by app/legal.tsx, before sign-in.'],
];

const check = process.argv.includes('--check');
let stale = false;

for (const [path, consumer] of targets) {
  const next = render(consumer);
  let current = '';
  try {
    current = readFileSync(path, 'utf8');
  } catch {
    /* first run */
  }
  if (current === next) continue;
  if (check) {
    console.error(`stale: ${path}`);
    stale = true;
  } else {
    writeFileSync(path, next);
    console.log(`wrote ${path}`);
  }
}

if (stale) {
  console.error('Run `node tools/legal/sync.mjs` and commit the result.');
  process.exit(1);
}
if (!check) console.log(`LEGAL_VERSION ${version}`);
