import type { GeneratedCase } from './case.js';

/**
 * How the accused PRESENTS, and why the server rolls it.
 *
 * FAULT's central claim is that it can tell you something true about your own
 * judgement. That claim rests entirely on one property: the things a juror
 * reads off a defendant's body must carry no information about whether they
 * did it. If they did, a juror who followed them would be right, "bias" would
 * be skill, and the Juror Record would be flattering people for pattern
 * matching.
 *
 * There are three such channels, and this module owns all of them:
 *
 *   appearance   the face          hard        <-> disarming
 *   demeanour    the body          closed      <-> open
 *   oddity       the strangeness   unremarkable<-> uncanny
 *
 * WHY THE MODEL IS NOT ALLOWED TO SET THESE
 * -----------------------------------------
 * `appearance` used to be generated by Groq, with the prompt asking it to
 * "roll it as if blind to the verdict". That instruction is the same shape as
 * the ambiguity instruction the generator already learned it cannot trust —
 * and this one is worse, because a violation is invisible. A docket where
 * guilty defendants are 8 points shiftier looks completely normal case by
 * case, and silently turns appearance_bias into an accuracy score.
 *
 * The model is a good writer and a hopeless randomiser. It has read a great
 * many stories in which the guilty man will not meet your eye, and it will
 * reproduce that correlation while sincerely reporting that it did not.
 *
 * So the numbers are drawn HERE, from a source that has never seen the
 * verdict — and `stripPresentation` removes whatever the model volunteered
 * before it can reach a case. That is not belt and braces; the model returns
 * these fields whether or not the prompt asks for them.
 */

/** The three channels a juror reads and none of which mean anything. */
export interface Presentation {
  appearance: number;
  demeanour: number;
  oddity: number;
}

/**
 * A verdict-blind roll.
 *
 * Deliberately NOT `Math.random()` at the call site: taking a seed makes the
 * property testable. A test can generate ten thousand of these against
 * alternating verdicts and assert the correlation is nil, which is the only
 * way anyone will ever know this still holds in a year.
 */
export interface Roller {
  (): number;
}

/**
 * Centre-weighted, because people are.
 *
 * A flat distribution puts as many openly bizarre defendants in the dock as
 * ordinary ones, and a docket of extremes stops reading as a population and
 * starts reading as a freak show — at which point strangeness is no longer
 * something the player can be caught reacting to, because everyone is strange.
 *
 * Averaging three uniforms gives a rough bell: most people near the middle, a
 * thin tail at each end. The tails are where the measurement lives.
 */
function bell(roll: Roller): number {
  return ((roll() + roll() + roll()) / 3) * 100;
}

/**
 * Roll how a defendant presents.
 *
 * Takes a roller rather than reaching for Math.random so the property this
 * module exists to guarantee can actually be tested. Note what this function
 * does NOT take: the case, the verdict, the evidence, or anything derived from
 * them. It cannot correlate with guilt because it cannot see guilt — that is
 * the design, and the signature is the proof.
 */
export function rollPresentation(roll: Roller = Math.random): Presentation {
  return {
    appearance: bell(roll),
    demeanour: bell(roll),
    oddity: bell(roll),
  };
}

/**
 * Overwrite whatever the model said about the body.
 *
 * Applied to every generated case, on both the live and fallback paths. The
 * model is told to write the person; the server decides how they look, stand
 * and unsettle. Same move as `enforceCast` makes with names, and for the same
 * reason: where the model reliably will not comply, take the decision away
 * from it rather than asking louder.
 */
export function stripPresentation(generated: GeneratedCase, roll: Roller = Math.random): GeneratedCase {
  const rolled = rollPresentation(roll);
  generated.defendant.appearance = rolled.appearance;
  generated.defendant.demeanour = rolled.demeanour;
  generated.defendant.oddity = rolled.oddity;
  return generated;
}

/* ------------------------------------------------------------------ *
 * Reading the numbers back
 * ------------------------------------------------------------------ */

/**
 * The bands the bias scores compare.
 *
 * Wide enough that the middle of the population is excluded from both sides:
 * a juror is scored on how differently they treat the clearly-closed against
 * the clearly-open, not on noise around the mean.
 */
export const BANDS = {
  /** Faces below this read as unsettling; above the upper bound, disarming. */
  appearance: { low: 35, high: 65 },
  /** Bodies below this read as closed and defensive; above, open and still. */
  demeanour: { low: 35, high: 65 },
  /**
   * Oddity is asymmetric on purpose. "Unremarkable" is most of the population,
   * so the low band is broad; "strange enough to notice" is genuinely rare,
   * so the high band starts further out. Comparing the odd against the median
   * is the honest comparison — comparing them against the blandest tail would
   * inflate every score.
   */
  oddity: { low: 45, high: 72 },
} as const;

export type PresentationChannel = keyof typeof BANDS;

/**
 * How much more readily a juror convicts one end of a channel than the other.
 *
 * Positive means they convict the LOW end more — the hard-faced, the closed,
 * the unremarkable. Negative means the high end. Range -100..100.
 *
 * Returns 0 when either band is empty rather than pretending: a juror who has
 * never seen an openly strange defendant has no oddity bias yet, and reporting
 * one would be inventing a finding out of an absence.
 */
export function biasFor(
  verdicts: { convicted: boolean; value: number }[],
  channel: PresentationChannel,
): number {
  const { low, high } = BANDS[channel];
  const lowBand = verdicts.filter((v) => v.value <= low);
  const highBand = verdicts.filter((v) => v.value >= high);
  if (lowBand.length === 0 || highBand.length === 0) return 0;

  const rate = (set: typeof verdicts) =>
    (set.filter((v) => v.convicted).length / set.length) * 100;

  return rate(lowBand) - rate(highBand);
}

/**
 * What the court would say about a bias, in the court's voice.
 *
 * Never a number, and never an accusation. The record states what the pattern
 * is and lets the juror sit with it — the same discipline the outcome writer
 * follows. "Convicts the ones who will not meet their eye" is a fact about a
 * record; "you are prejudiced" is the game moralising, and it does not.
 */
export function describeBias(channel: PresentationChannel, score: number): string | null {
  const strong = Math.abs(score) > 20;
  if (!strong) return null;

  const towardLow = score > 0;
  switch (channel) {
    case 'appearance':
      return towardLow
        ? 'convicts defendants they find unsettling to look at more readily'
        : 'acquits defendants they find unsettling to look at more readily';
    case 'demeanour':
      return towardLow
        ? 'convicts defendants who sit closed and defensive more readily'
        : 'convicts defendants who meet the room openly more readily';
    case 'oddity':
      return towardLow
        ? 'convicts the unremarkable and spares the strange'
        : 'convicts defendants who strike them as strange more readily';
  }
}
