/**
 * FAULT — sound synthesis.
 *
 * Every sound in this game is generated by this script rather than licensed or
 * recorded, and that is a design decision as much as a practical one.
 *
 * FAULT's register is austere: a near-black room, a paper dossier, a clock you
 * cannot argue with. Stock library sound effects arrive with a genre attached —
 * a "gavel" sample is always a courtroom drama gavel, cinematic and confident.
 * What this room needs is duller and more physical than that: wood, paper,
 * distant traffic, a clock that is not trying to frighten you and does anyway.
 *
 * Synthesis also means: no licensing, no CDN, no missing-asset crash, every
 * sound tuned by editing a number, and about 40KB for the lot.
 *
 * Run:  node scripts/generate-sounds.mjs
 * Out:  assets/sound/*.wav  (16-bit mono PCM, 44.1k)
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = join(HERE, '..', 'assets', 'sound');

/**
 * Sample rate per sound, not one rate for all of them.
 *
 * Nyquist: a signal needs twice the sample rate of its highest frequency, and
 * no more. `room` is a drone with nothing above 180Hz — storing it at 44.1kHz
 * spends five times the bytes to represent silence above 4kHz. Picking the
 * rate per sound takes the whole set from 1.2MB to under 200KB with no
 * audible difference, and an app bundle is not the place to be generous.
 */
const RATES = {
  room: 8000,     // lowpassed at 180Hz
  tension: 8000,  // lowpassed at 400Hz
  tick: 16000,    // has content to ~4.2kHz
  gavel: 16000,   // lowpassed at 2.6kHz
  paper: 16000,   // the brightest thing here, to 7kHz
  exhibit: 8000,  // lowpassed at 3.2kHz
  open: 8000,     // lowpassed at 900Hz
  stamp: 8000,    // lowpassed at 2.2kHz
};

/** Set per render; every helper below reads it. */
let RATE = 44100;

// ── WAV container ─────────────────────────────────────────────────────────

function toWav(samples) {
  const data = Buffer.alloc(samples.length * 2);
  for (let i = 0; i < samples.length; i++) {
    // Clip rather than wrap: a wrapped sample is a loud click.
    const s = Math.max(-1, Math.min(1, samples[i]));
    data.writeInt16LE(Math.round(s * 32767), i * 2);
  }

  const header = Buffer.alloc(44);
  header.write('RIFF', 0);
  header.writeUInt32LE(36 + data.length, 4);
  header.write('WAVE', 8);
  header.write('fmt ', 12);
  header.writeUInt32LE(16, 16); // PCM chunk size
  header.writeUInt16LE(1, 20); // format: PCM
  header.writeUInt16LE(1, 22); // channels: mono
  header.writeUInt32LE(RATE, 24);
  header.writeUInt32LE(RATE * 2, 28); // byte rate
  header.writeUInt16LE(2, 32); // block align
  header.writeUInt16LE(16, 34); // bits
  header.write('data', 36);
  header.writeUInt32LE(data.length, 40);

  return Buffer.concat([header, data]);
}

const seconds = (n) => Math.floor(n * RATE);

// ── Building blocks ───────────────────────────────────────────────────────

const sine = (t, hz) => Math.sin(2 * Math.PI * hz * t);

/** Deterministic noise — the same build always produces the same files. */
let seed = 12345;
function noise() {
  seed = (seed * 1103515245 + 12345) & 0x7fffffff;
  return (seed / 0x3fffffff) - 1;
}

/** One-pole lowpass. Rounds every hard edge off; nothing here should be bright. */
function lowpass(samples, cutoffHz) {
  const rc = 1 / (2 * Math.PI * cutoffHz);
  const a = (1 / RATE) / (rc + 1 / RATE);
  let last = 0;
  return samples.map((s) => (last = last + a * (s - last)));
}

function highpass(samples, cutoffHz) {
  const rc = 1 / (2 * Math.PI * cutoffHz);
  const a = rc / (rc + 1 / RATE);
  let prevIn = 0;
  let prevOut = 0;
  return samples.map((s) => {
    const out = a * (prevOut + s - prevIn);
    prevIn = s;
    prevOut = out;
    return out;
  });
}

/** Exponential decay — how physical objects actually stop. */
const decay = (t, rate) => Math.exp(-t * rate);

/** A short fade at both ends so a file never starts or ends on a click. */
function deClick(samples, ms = 4) {
  const n = Math.min(seconds(ms / 1000), Math.floor(samples.length / 2));
  for (let i = 0; i < n; i++) {
    const g = i / n;
    samples[i] *= g;
    samples[samples.length - 1 - i] *= g;
  }
  return samples;
}

function render(durationSeconds, fn) {
  const n = seconds(durationSeconds);
  const out = new Array(n);
  for (let i = 0; i < n; i++) out[i] = fn(i / RATE, i);
  return out;
}

// ── The palette ───────────────────────────────────────────────────────────

const SOUNDS = {
  /**
   * The room. A loopable bed for the whole case: distant low traffic, the
   * building's own hum, nothing you would notice until it stops.
   *
   * Deliberately almost inaudible. It exists so that the 15-second tension
   * tone has something to rise out of.
   */
  room: () => {
    const dur = 8; // loops
    let s = render(dur, (t) => {
      const hum = sine(t, 50) * 0.05 + sine(t, 100) * 0.015; // mains-ish
      const rumble = noise() * 0.08;
      return hum + rumble;
    });
    s = lowpass(s, 180);
    // Match the ends so the loop point does not thump.
    const fade = seconds(0.5);
    for (let i = 0; i < fade; i++) {
      const g = i / fade;
      s[i] = s[i] * g + s[s.length - 1 - i] * (1 - g);
    }
    return deClick(s, 20);
  },

  /**
   * 15 seconds left (GDD 2.2). A low tone that does not resolve.
   *
   * Two sines a few Hz apart, so they beat against each other — the ear reads
   * an interval that will not settle as unease, without the sound itself being
   * loud or dramatic. It is the same trick a fridge uses at 3am.
   */
  tension: () => {
    const dur = 4; // loops under the last 15s
    let s = render(dur, (t) => {
      const swell = Math.min(1, t / 1.2);
      const a = sine(t, 73);
      const b = sine(t, 76.5); // ~3.5Hz beat
      const pulse = 0.75 + 0.25 * sine(t, 0.9);
      return (a + b) * 0.16 * swell * pulse;
    });
    s = lowpass(s, 400);
    const fade = seconds(0.4);
    for (let i = 0; i < fade; i++) {
      const g = i / fade;
      s[i] = s[i] * g + s[s.length - 1 - i] * (1 - g);
    }
    return deClick(s, 15);
  },

  /**
   * The last five seconds. A clock, not a beep.
   *
   * Escapement click: a noise transient through a bandpass-ish shape, plus a
   * short woody body. Quiet, dry, and impossible to ignore once you have
   * noticed it.
   */
  tick: () => {
    let s = render(0.09, (t) => {
      const click = noise() * decay(t, 320);
      const body = sine(t, 1800) * decay(t, 180) * 0.25;
      return (click * 0.5 + body) * 0.55;
    });
    s = highpass(lowpass(s, 4200), 700);
    return deClick(s, 2);
  },

  /**
   * The verdict. Wood on wood — a gavel that is not performing.
   *
   * Hard transient, low body, fast decay, and no ring: this room has no
   * reverb, and a gavel that rang would sound like television.
   */
  gavel: () => {
    let s = render(0.5, (t) => {
      const strike = noise() * decay(t, 140) * 0.6;
      const body = (sine(t, 92) + sine(t, 138) * 0.4) * decay(t, 16) * 0.7;
      const knock = sine(t, 320) * decay(t, 60) * 0.25;
      return strike + body + knock;
    });
    s = lowpass(s, 2600);
    return deClick(s, 2);
  },

  /**
   * Paper. Turning a tab, moving through the dossier.
   *
   * Filtered noise with a fast, uneven envelope — the sound of a page being
   * handled by someone in a hurry.
   */
  paper: () => {
    let s = render(0.28, (t) => {
      const rustle = noise() * decay(t, 11);
      const grain = noise() * decay(t, 40) * 0.4 * (0.5 + 0.5 * sine(t, 31));
      return (rustle + grain) * 0.4;
    });
    s = highpass(lowpass(s, 7000), 1400);
    return deClick(s, 3);
  },

  /**
   * Picking an exhibit up off the table. Shorter and harder than paper —
   * something with weight being moved.
   */
  exhibit: () => {
    let s = render(0.22, (t) => {
      const tap = noise() * decay(t, 190) * 0.5;
      const body = sine(t, 210) * decay(t, 40) * 0.4;
      return tap + body;
    });
    s = lowpass(s, 3200);
    return deClick(s, 2);
  },

  /**
   * A door, a file landing, a screen arriving. The game's page turn.
   * Low, brief, and slightly heavy — everything in this game is heavier than
   * it needs to be.
   */
  open: () => {
    let s = render(0.6, (t) => {
      const swell = (1 - decay(t, 9)) * decay(t, 3.2);
      const tone = (sine(t, 58) + sine(t, 87) * 0.3) * swell;
      const air = noise() * swell * 0.12;
      return (tone + air) * 0.5;
    });
    s = lowpass(s, 900);
    return deClick(s, 6);
  },

  /**
   * Merit, a mission claimed, a promotion. The only sound in the game allowed
   * to be even slightly pleasant — and it still does not resolve upward,
   * because nothing in FAULT congratulates you.
   */
  stamp: () => {
    let s = render(0.35, (t) => {
      const press = noise() * decay(t, 90) * 0.45;
      const thud = sine(t, 120) * decay(t, 22) * 0.5;
      const ink = sine(t, 240) * decay(t, 30) * 0.18;
      return press + thud + ink;
    });
    s = lowpass(s, 2200);
    return deClick(s, 2);
  },
};

// ── Write ─────────────────────────────────────────────────────────────────

mkdirSync(OUT, { recursive: true });

let total = 0;
for (const [name, make] of Object.entries(SOUNDS)) {
  RATE = RATES[name] ?? 44100;
  // Noise is seeded per sound so a rate change does not reshuffle every file.
  seed = 12345;
  const wav = toWav(make());
  const path = join(OUT, `${name}.wav`);
  writeFileSync(path, wav);
  total += wav.length;
  console.log(`  ${name.padEnd(9)} ${(wav.length / 1024).toFixed(1).padStart(6)} KB  ${String(RATE).padStart(5)} Hz`);
}
console.log(`  ${''.padEnd(9)} ${'──────'}`);
console.log(`  ${'total'.padEnd(9)} ${(total / 1024).toFixed(1).padStart(6)} KB`);
